### ISSUE TITLE
Bug: Can't handle photos in secret chat

### ISSUE THREAD

**Issue by dustessavdh** [tgsnake/core#3]
I was trying out the secret chat feature, but I discovered a bug with receiving photos and videos. I haven't checked all other types, but documents and stickers worked for me.
## Bug
When receiving a photo in a secret chat I get the following error:
```js
(@tgsnake/core) debug - [3] Receive 100 bytes data 8/9/2023 0:17:46.470
(@tgsnake/core) debug - [33] Unpacking 88 bytes packet. 8/9/2023 0:17:46.470
(@tgsnake/core) debug - [5] Decrypting 64 bytes data with AES-256-IGE 8/9/2023 0:17:46.470
(@tgsnake/core) debug - [10] Reading TLObject with id: 347773c5 (Raw.Pong) 8/9/2023 0:17:46.471
(@tgsnake/core) debug - [34] Reveive 1 data. 8/9/2023 0:17:46.472
(@tgsnake/core) debug - [35] Setting server time: 1694125067. 8/9/2023 0:17:46.472
(@tgsnake/core) debug - [42] Got Pong and msg id is: 7276211758098808832. 8/9/2023 0:17:46.472
(@tgsnake/core) debug - [3] Receive 1240 bytes data 8/9/2023 0:17:50.617
(@tgsnake/core) debug - [3] Receive 1484 bytes data 8/9/2023 0:17:50.617
(@tgsnake/core) debug - [33] Unpacking 2712 bytes packet. 8/9/2023 0:17:50.618
(@tgsnake/core) debug - [5] Decrypting 2688 bytes data with AES-256-IGE 8/9/2023 0:17:50.618
(@tgsnake/core) debug - [10] Reading TLObject with id: 74ae4240 (Raw.Updates) 8/9/2023 0:17:50.632
(@tgsnake/core) debug - [10] Reading TLObject with id: 1cb5c415 (Primitive.Vector) 8/9/2023 0:17:50.632
(@tgsnake/core) debug - [10] Reading TLObject with id: 12bcbd9a (Raw.UpdateNewEncryptedMessage) 8/9/2023 0:17:50.633
(@tgsnake/core) debug - [10] Reading TLObject with id: ed18c118 (Raw.EncryptedMessage) 8/9/2023 0:17:50.633
(@tgsnake/core) debug - [10] Reading TLObject with id: a8008cd8 (Raw.EncryptedFile) 8/9/2023 0:17:50.633
(@tgsnake/core) debug - [10] Reading TLObject with id: 1cb5c415 (Primitive.Vector) 8/9/2023 0:17:50.634
(@tgsnake/core) debug - [10] Reading TLObject with id: 1cb5c415 (Primitive.Vector) 8/9/2023 0:17:50.634
(@tgsnake/core) debug - [34] Reveive 1 data. 8/9/2023 0:17:50.634
(@tgsnake/core) debug - [37] Add msg id 7276211778053821441 to pending acks. 8/9/2023 0:17:50.634
(@tgsnake/core) debug - [43] Handling update Updates. 8/9/2023 0:17:50.634
(@tgsnake/core) debug - [76] Updating 0 peers 8/9/2023 0:17:50.635
(@tgsnake/core) debug - [76] Updating 0 peers 8/9/2023 0:17:50.635
(@tgsnake/core) debug - [110] Getting secret chat by id: 1759419282 8/9/2023 0:17:50.635
(@tgsnake/core) debug - [5] Decrypting 2512 bytes data with AES-256-IGE 8/9/2023 0:17:50.635
(@tgsnake/core) debug - [10] Reading TLObject with id: 1be31789 (Raw.DecryptedMessageLayer17) 8/9/2023 0:17:50.649
(@tgsnake/core) debug - [10] Reading TLObject with id: 91cc4674 (Raw.DecryptedMessage73) 8/9/2023 0:17:50.649
(@tgsnake/core) debug - [10] Reading TLObject with id: f1fa8d78 (Raw.DecryptedMessageMediaPhoto45) 8/9/2023 0:17:50.649
(@tgsnake/core) debug - [5] Decrypting 2512 bytes data with AES-256-IGE 8/9/2023 0:17:50.655
(@tgsnake/core) debug - [10] Reading TLObject with id: c4f295a2 (undefined) 8/9/2023 0:17:50.667
REDACTED\node_modules\@tgsnake\core\lib\src\raw\core\TLObject.js:52
        throw new Error("name of module can't be undefined");
              ^
Error: name of module can't be undefined
    at getModule (REDACTED\node_modules\@tgsnake\core\lib\src\raw\core\TLObject.js:52:15)
    at Function.read (REDACTED\node_modules\@tgsnake\core\lib\src\raw\core\TLObject.js:91:30)
    at Object.unpack (REDACTED\node_modules\@tgsnake\core\lib\src\crypto\SecretChat.js:104:43)
    at SecretChat.decrypt (REDACTED\node_modules\@tgsnake\core\lib\src\session\secretChats\SecretChat.js:485:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.generate (REDACTED\node_modules\@tgsnake\core\lib\src\raw\core\UpdateSecretChat.js:35:27)
    at async Client._handleSecretChatUpdate (REDACTED\node_modules\@tgsnake\core\lib\src\client\Client.js:179:27)
    at async Client.handleUpdate (REDACTED\node_modules\@tgsnake\core\lib\src\client\Client.js:161:43)
```

I tracked it down to where it starts going into a path that it can't recover from:
https://github.com/tgsnake/core/blob/f992c94283956a7cda52822dae7b4072d05465db/src/session/secretChats/SecretChat.ts#L561-L571

It fails to unpack it and tries to decrypt it again, because it doesn't match the if check.
After adding a log statement there it gives the following error:
```js
(@tgsnake/core) debug - [10] Reading TLObject with id: f1fa8d78 (Raw.DecryptedMessageMediaPhoto45) 8/9/2023 0:17:50.649
(@tgsnake/core) error - [constructor of SecurityCheckMismatch] {
  "_": "SecurityCheckMismatch",
  "stack": "Error: A security check mismatch has occurred.
  at Function.check (REDACTED\\node_modules\\@tgsnake\\core\\lib\\src\\errors\\index.js:243:19)
  at Object.unpack (REDACTED\\node_modules\\@tgsnake\\core\\lib\\src\\crypto\\SecretChat.js:115:38)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async SecretChat.decrypt (REDACTED\\node_modules\\@tgsnake\\core\\lib\\src\\session\\secretChats\\SecretChat.js:477:33)
  at async Function.generate (REDACTED\\node_modules\\@tgsnake\\core\\lib\\src\\raw\\core\\UpdateSecretChat.js:35:27)\n    
  at async Client._handleSecretChatUpdate (REDACTED\\node_modules\\@tgsnake\\core\\lib\\src\\client\\Client.js:179:27)\n    
  at async Client.handleUpdate (REDACTED\\node_modules\\@tgsnake\\core\\lib\\src\\client\\Client.js:161:43)",
  "message": "A security check mismatch has occurred.",
  "description": "Given message key is not equal with client side"
} 8/9/2023 0:17:50.653
(@tgsnake/core) debug - [5] Decrypting 2512 bytes data with AES-256-IGE 8/9/2023 0:17:50.655
```

## Expected behaviour

It depends. I think it should handle the pictures, because it's a new secret chat and receiving messages works. The moment it receives a photo it crashes. So I think it should handle it and not crash.

If it does indeed have a `SecurityCheckMismatch`. I think it should be handled as the `FingerprintMismatch` and get destroyed because currently it's trying to unpack it with `mtproto` set to `1`.

## System info
OS: Windows
package version: 1.10.0
npm version: 8.19.1
node version: v16.14.2

**Comment by dustessavdh** [comment]
My temporary workaround is to comment out the following line:
https://github.com/tgsnake/core/blob/f992c94283956a7cda52822dae7b4072d05465db/src/crypto/SecretChat.ts#L147-L150
Bad practice, but it seems to be working after this.

**Comment by butthx** [comment]
Thank you for helping us by reporting the bug. But can you post a sample code and answer some of these questions? 
1. Are use string session class?
2. Did the error appear after you restarted your program?

With some of the explanations above, I tried to fix the bug but we need more information about the bug by answering the question above.

**Comment by dustessavdh** [comment]
I'm indeed using string sessions. It happens during and after.
I replicated the issue with the following code:
```js
const { Client, Raw } = require('@tgsnake/core');
const { StringSession } = require('@tgsnake/core/lib/src/storage');
const prompts = require('prompts'); // npm i prompts
require('dotenv').config(); // npm i dotenv

const client = new Client(
  new StringSession(''),
  process.env.API_HASH,
  process.env.API_ID
);

async function main() {
  await client.start({
    phoneNumber: async () => {
      return process.env.PHONE_NUMBER;
    },
    code: async () => {
      const response = await prompts({
        type: 'text',
        name: 'value',
        message: 'Enter your code:',
      });
      return response.value;
    },
  });

  await client.addHandler(async (update) => {
    console.log(update.className);
    if (update instanceof Raw.UpdateShortMessage) {
      if (update.message === 'Secret chat') {
        await client.startSecretChat(update.userId);
      }
    }
  });
}

main();
```

Then I used a different account to send me messages.
After running the script and signing in, I followed these steps:
1. send a message like `hi` to check if it is receiving messages
2. send a message with `Secret chat`
3. send a message like `hi` in the new secret chat.
4. send a photo using the built-in camera in the official telegram on the play store
After step 4 it crashes with the error I mentioned

**Comment by butthx** [comment]
Hi! I have push new update and i have test to receive photos, text, documents in secret chat it worked.

This seems to be the same bug as #1, somehow the security check position is affected.

You can try to install new update in npm or build from source.

**Comment by butthx** [comment]
Hello, I consider this issue to be resolved on your side and on the framework side because there has been a new commit `(1.10.1)` regarding this bug and there has been no response from you.

I'll close this issue and mark it with solved.

You can open this issue again if you still faced that error.

Thank you for the bug report, I really appreciate your report.
